Indented the remaining functions for better code visibility and understandability

diff --git a/functions_goto b/functions_goto
--- a/functions_goto
+++ b/functions_goto
@@ -441,169 +441,169 @@ function gthist {
 }
 
 function goToPrevDir {
-if [[ $prev_dir == '' ]]; then
-    echo 'No directory had previously been visited in the current session!';
-    return 1;
-fi
-gotoDir "$prev_dir";
-return 0;
+    if [[ $prev_dir == '' ]]; then
+	echo 'No directory had previously been visited in the current session!';
+	return 1;
+    fi
+    gotoDir "$prev_dir";
+    return 0;
 }
 
 function addToFavorites {
-#temporary file used for various operations (to be removed each time the operation it is used in finishes)
-temp_file=$script_dir/.temp;
-# Step 1: check if the user entered an argument or not
-# - the argument is a relative/absolute path of a directory that should be added to the favorite dirs (if it exists)
-# - if no argument was entered, the current directory will be added to favorites
-if [[ ! -z "$1" ]]; then
-    if [[ ! -d "$1" ]]; then
-	echo 'The directory does not exist or has been deleted. Cannot add to favorites.';
-	return 1;
-    fi
-    cd "$1";
-    dir_to_add=`pwd`;
-    cd - > /dev/null;
-else
-    dir_to_add=`pwd`;
-fi
-
-# Step 2: append the path to the favorites file (create it if it does not exist)
-#
-# helper function that moves the entry from the persistent history file to the excluded history file
-function excludeFromPersistentHistory {
-    # check if the entry is included in the persistent history file (if yes, move to the excluded history file and re-sort the persistent history file)
-    entryToExclude=`grep "$dir_to_add"';' "$p_hist_file"`;
-    if [[ $? == 0 ]]; then
-	grep -v "$entryToExclude" "$p_hist_file" > "$temp_file";
-	# normally sorting would not be required (the persistent history file is already sorted and should remain so; it's just a safety precaution)
-	sort -n -r -k2 -t ';' "$temp_file" > "$p_hist_file";
-	rm "$temp_file";
-	# history should be consolidated again
-	cat "$r_hist_file" > "$hist_file";
-	head -"$p_hist_max_rows" "$p_hist_file" | cut -f 1 -d ';' >> "$hist_file";
-	# update excluded history file
-	echo "$entryToExclude" >> "$e_hist_file";
+    #temporary file used for various operations (to be removed each time the operation it is used in finishes)
+    temp_file=$script_dir/.temp;
+    # Step 1: check if the user entered an argument or not
+    # - the argument is a relative/absolute path of a directory that should be added to the favorite dirs (if it exists)
+    # - if no argument was entered, the current directory will be added to favorites
+    if [[ ! -z "$1" ]]; then
+	if [[ ! -d "$1" ]]; then
+	    echo 'The directory does not exist or has been deleted. Cannot add to favorites.';
+	    return 1;
+	fi
+	cd "$1";
+	dir_to_add=`pwd`;
+	cd - > /dev/null;
     else
-	# if file is not already included in persistent history, just add it to the excluded history file (with number of visits 0 as the directory hasn't been visited yet)
-	echo "$dir_to_add"';0' >> "$e_hist_file";
+	dir_to_add=`pwd`;
     fi
-}
-if [[  -f "$fav_file" ]]; then
-    grep -x "$dir_to_add" "$fav_file" > /dev/null;
-    if [[ $? != 0 ]]; then
+
+    # Step 2: append the path to the favorites file (create it if it does not exist)
+    #
+    # helper function that moves the entry from the persistent history file to the excluded history file
+    function excludeFromPersistentHistory {
+	# check if the entry is included in the persistent history file (if yes, move to the excluded history file and re-sort the persistent history file)
+	entryToExclude=`grep "$dir_to_add"';' "$p_hist_file"`;
+	if [[ $? == 0 ]]; then
+	    grep -v "$entryToExclude" "$p_hist_file" > "$temp_file";
+	    # normally sorting would not be required (the persistent history file is already sorted and should remain so; it's just a safety precaution)
+	    sort -n -r -k2 -t ';' "$temp_file" > "$p_hist_file";
+	    rm "$temp_file";
+	    # history should be consolidated again
+	    cat "$r_hist_file" > "$hist_file";
+	    head -"$p_hist_max_rows" "$p_hist_file" | cut -f 1 -d ';' >> "$hist_file";
+	    # update excluded history file
+	    echo "$entryToExclude" >> "$e_hist_file";
+	else
+	    # if file is not already included in persistent history, just add it to the excluded history file (with number of visits 0 as the directory hasn't been visited yet)
+	    echo "$dir_to_add"';0' >> "$e_hist_file";
+	fi
+    }
+    if [[  -f "$fav_file" ]]; then
+	grep -x "$dir_to_add" "$fav_file" > /dev/null;
+	if [[ $? != 0 ]]; then
+	    echo $dir_to_add >> "$fav_file";
+	    echo "Directory $dir_to_add added to favorites";
+	    excludeFromPersistentHistory;
+	    return 0;
+	else
+	    echo "Directory $dir_to_add already added to favorites";
+	    return 1;
+	fi
+    else
 	echo $dir_to_add >> "$fav_file";
 	echo "Directory $dir_to_add added to favorites";
 	excludeFromPersistentHistory;
 	return 0;
-    else
-	echo "Directory $dir_to_add already added to favorites";
-	return 1;
     fi
-else
-    echo $dir_to_add >> "$fav_file";
-    echo "Directory $dir_to_add added to favorites";
-    excludeFromPersistentHistory;
-    return 0;
-fi
 }
 #
 # this function removes the entry from favorites and moves it back to persistent history
 function removeFromFavorites {
-#temporary file used for various operations (to be removed each time the operation it is used in finishes)
-temp_file=$script_dir/.temp;
-# Step 1: check if the favorites file exists and is not empty
-if [[ ! -f "$fav_file" ]]; then
-    echo "Error! The favorites file $fav_file does not exist or has been deleted";
-    return 1;
-fi
-if [[ ! -s "$fav_file" ]]; then
-    echo "File $fav_file is empty! Nothing to remove";
-    return 1;
-fi
-# Step 2: display the file and prompt the user to choose the line to be deleted
-function displayFavoritesFile {
-clear;
-cat -n "$fav_file";
-echo;
-echo 'Enter the number of the entry to be removed';
-echo 'Enter q or Q to quit';
-echo;
-}
-displayFavoritesFile;
-read dir_nr;
-# Step 3: check the input entered by user. If should be either:
-# - a number between 1 and and the number of entries contained in the file
-# - a character that triggers quitting the function
-#
-tempVar=`wc -l "$fav_file"`;
-currentNumberOfEntries=`echo $tempVar | cut -f 1 -d ' '`;
-while [[ '1' == '1' ]];
-do
-    if [[ $dir_nr =~  $nonNegativeInteger     ]] &&
-       [[ $dir_nr -ge 1                       ]] &&
-       [[ $dir_nr -le $currentNumberOfEntries ]]; then
-	break;
-    elif [[ $dir_nr == 'q' ]] || [[ $dir_nr == 'Q' ]]; then
-	clear;
-	echo 'Aborted!';
-	return 0;
-    else
-	displayFavoritesFile;
-	echo 'Invalid value! Please try again.';
-	echo;
-	read dir_nr;
+    #temporary file used for various operations (to be removed each time the operation it is used in finishes)
+    temp_file=$script_dir/.temp;
+    # Step 1: check if the favorites file exists and is not empty
+    if [[ ! -f "$fav_file" ]]; then
+	echo "Error! The favorites file $fav_file does not exist or has been deleted";
+	return 1;
     fi
-done
-# Step 4: remove the entry from the excluded history file
-fav_dir_to_remove=`sed "$dir_nr"'q;d' "$fav_file"`;
-excl_dir_to_remove=`grep "$fav_dir_to_remove"';' "$e_hist_file"`;
-visitsCount=`echo "$excl_dir_to_remove" | cut -f 2 -d ';'`;
-grep -v "$excl_dir_to_remove" "$e_hist_file" > "$temp_file";
-mv "$temp_file" "$e_hist_file";
-# Also move the entry back to the persistent history file if it has at least one visit
-if [[ $visitsCount -gt 0 ]]; then
-    echo $excl_dir_to_remove >> "$p_hist_file";
-    # Always sort the persistent history file when it is modified
-    sort -n -r -k2 -t ';' "$p_hist_file" > "$temp_file";
-    mv "$temp_file" "$p_hist_file";
-    # history should be consolidated again
-    cat "$r_hist_file" > "$hist_file";
-    head -"$p_hist_max_rows" "$p_hist_file" | cut -f 1 -d ';' >> "$hist_file";
-fi
-# Step 5: delete the entry
-sed "$dir_nr"'d' "$fav_file" > "$temp_file";
-mv "$temp_file" "$fav_file";
-clear;
-echo 'Entry removed from the favorites file';
+    if [[ ! -s "$fav_file" ]]; then
+	echo "File $fav_file is empty! Nothing to remove";
+	return 1;
+    fi
+    # Step 2: display the file and prompt the user to choose the line to be deleted
+    function displayFavoritesFile {
+	clear;
+	cat -n "$fav_file";
+	echo;
+	echo 'Enter the number of the entry to be removed';
+	echo 'Enter q or Q to quit';
+	echo;
+    }
+    displayFavoritesFile;
+    read dir_nr;
+    # Step 3: check the input entered by user. If should be either:
+    # - a number between 1 and and the number of entries contained in the file
+    # - a character that triggers quitting the function
+    #
+    tempVar=`wc -l "$fav_file"`;
+    currentNumberOfEntries=`echo $tempVar | cut -f 1 -d ' '`;
+    while [[ '1' == '1' ]];
+    do
+	if [[ $dir_nr =~  $nonNegativeInteger     ]] &&
+	       [[ $dir_nr -ge 1                       ]] &&
+	       [[ $dir_nr -le $currentNumberOfEntries ]]; then
+	    break;
+	elif [[ $dir_nr == 'q' ]] || [[ $dir_nr == 'Q' ]]; then
+	    clear;
+	    echo 'Aborted!';
+	    return 0;
+	else
+	    displayFavoritesFile;
+	    echo 'Invalid value! Please try again.';
+	    echo;
+	    read dir_nr;
+	fi
+    done
+    # Step 4: remove the entry from the excluded history file
+    fav_dir_to_remove=`sed "$dir_nr"'q;d' "$fav_file"`;
+    excl_dir_to_remove=`grep "$fav_dir_to_remove"';' "$e_hist_file"`;
+    visitsCount=`echo "$excl_dir_to_remove" | cut -f 2 -d ';'`;
+    grep -v "$excl_dir_to_remove" "$e_hist_file" > "$temp_file";
+    mv "$temp_file" "$e_hist_file";
+    # Also move the entry back to the persistent history file if it has at least one visit
+    if [[ $visitsCount -gt 0 ]]; then
+	echo $excl_dir_to_remove >> "$p_hist_file";
+	# Always sort the persistent history file when it is modified
+	sort -n -r -k2 -t ';' "$p_hist_file" > "$temp_file";
+	mv "$temp_file" "$p_hist_file";
+	# history should be consolidated again
+	cat "$r_hist_file" > "$hist_file";
+	head -"$p_hist_max_rows" "$p_hist_file" | cut -f 1 -d ';' >> "$hist_file";
+    fi
+    # Step 5: delete the entry
+    sed "$dir_nr"'d' "$fav_file" > "$temp_file";
+    mv "$temp_file" "$fav_file";
+    clear;
+    echo 'Entry removed from the favorites file';
 }
 
 # This function is used to enter navigation mode
 # In this mode the user can repeatedly visit directories by only entering the name of each folder (absolute path, relative path - including wildcards)
 # It is also possible to access other functions like history/favorites, goto previous directory etc.
 function navigate {
-while [[ '1' == '1' ]]; do
-    echo;
-    echo 'Enter the path of the directory you want to visit. ';
-    echo 'Other available options: ';
-    echo ':h - to enter history menu';
-    echo ':f - to enter favorites menu';
-    echo ':p - to go to the previously visited directory';
-    echo ':q - to quit navigation mode';
-    echo;
-    read dir_to_visit;
-    clear;
-    if [[ $dir_to_visit == ':h' ]]; then
-	gthist;
-    elif [[ $dir_to_visit == ':f' ]]; then
-	gthist -f;
-    elif [[ $dir_to_visit == ':p' ]]; then
-	goToPrevDir;
-    elif [[ $dir_to_visit == ':q' ]]; then
-	echo 'You exited navigation mode';
-	return 0;
-    else
-	echo 'Entered argument:'"$dir_to_visit";
-	gotoDir "`echo $dir_to_visit`";
-    fi
-done
+    while [[ '1' == '1' ]]; do
+	echo;
+	echo 'Enter the path of the directory you want to visit. ';
+	echo 'Other available options: ';
+	echo ':h - to enter history menu';
+	echo ':f - to enter favorites menu';
+	echo ':p - to go to the previously visited directory';
+	echo ':q - to quit navigation mode';
+	echo;
+	read dir_to_visit;
+	clear;
+	if [[ $dir_to_visit == ':h' ]]; then
+	    gthist;
+	elif [[ $dir_to_visit == ':f' ]]; then
+	    gthist -f;
+	elif [[ $dir_to_visit == ':p' ]]; then
+	    goToPrevDir;
+	elif [[ $dir_to_visit == ':q' ]]; then
+	    echo 'You exited navigation mode';
+	    return 0;
+	else
+	    echo 'Entered argument:'"$dir_to_visit";
+	    gotoDir "`echo $dir_to_visit`";
+	fi
+    done
 }
